// Catálogo de funções para a biblioteca e as dicas de sintaxe: [nome canônico, categoria, argumentos, descrição].
// Os nomes exibidos vêm de formulas.js (pt-BR); argumentos entre colchetes são opcionais.
import { nomeLocal } from './formulas.js'

const L = [
  ['SUM', 'Matemática', 'núm1; [núm2]; …', 'Soma os números e intervalos informados.'],
  ['SUMIF', 'Matemática', 'intervalo; critério; [intervalo_soma]', 'Soma as células que atendem a um critério.'],
  ['SUMIFS', 'Matemática', 'intervalo_soma; intervalo1; critério1; …', 'Soma com vários critérios (todos devem ser atendidos).'],
  ['SUMPRODUCT', 'Matemática', 'matriz1; [matriz2]; …', 'Soma dos produtos dos elementos correspondentes (ex.: quantidade × preço).'],
  ['SUMSQ', 'Matemática', 'núm1; [núm2]; …', 'Soma dos quadrados.'],
  ['PRODUCT', 'Matemática', 'núm1; [núm2]; …', 'Multiplica os números informados.'],
  ['ROUND', 'Matemática', 'núm; casas', 'Arredonda para o número de casas decimais indicado.'],
  ['ROUNDUP', 'Matemática', 'núm; casas', 'Arredonda para cima, afastando de zero.'],
  ['ROUNDDOWN', 'Matemática', 'núm; casas', 'Arredonda para baixo, em direção a zero.'],
  ['CEILING', 'Matemática', 'núm; significância', 'Arredonda para cima até o múltiplo da significância (ex.: chapas, barras).'],
  ['FLOOR', 'Matemática', 'núm; significância', 'Arredonda para baixo até o múltiplo da significância.'],
  ['MROUND', 'Matemática', 'núm; múltiplo', 'Arredonda para o múltiplo mais próximo.'],
  ['INT', 'Matemática', 'núm', 'Parte inteira, arredondando para baixo.'],
  ['TRUNC', 'Matemática', 'núm; [casas]', 'Remove a parte decimal sem arredondar.'],
  ['MOD', 'Matemática', 'núm; divisor', 'Resto da divisão.'],
  ['QUOTIENT', 'Matemática', 'numerador; denominador', 'Parte inteira da divisão.'],
  ['ABS', 'Matemática', 'núm', 'Valor absoluto.'],
  ['SIGN', 'Matemática', 'núm', 'Sinal do número: 1, 0 ou −1.'],
  ['SQRT', 'Matemática', 'núm', 'Raiz quadrada.'],
  ['POWER', 'Matemática', 'base; expoente', 'Potência (equivale ao operador ^).'],
  ['EXP', 'Matemática', 'núm', 'e elevado à potência indicada.'],
  ['LN', 'Matemática', 'núm', 'Logaritmo natural.'],
  ['LOG', 'Matemática', 'núm; [base]', 'Logaritmo na base indicada (padrão 10).'],
  ['LOG10', 'Matemática', 'núm', 'Logaritmo na base 10.'],
  ['PI', 'Matemática', '', 'O número π.'],
  ['SIN', 'Matemática', 'ângulo_rad', 'Seno (ângulo em radianos).'],
  ['COS', 'Matemática', 'ângulo_rad', 'Cosseno (ângulo em radianos).'],
  ['TAN', 'Matemática', 'ângulo_rad', 'Tangente (ângulo em radianos).'],
  ['ASIN', 'Matemática', 'núm', 'Arco seno, em radianos.'],
  ['ACOS', 'Matemática', 'núm', 'Arco cosseno, em radianos.'],
  ['ATAN', 'Matemática', 'núm', 'Arco tangente, em radianos.'],
  ['ATAN2', 'Matemática', 'x; y', 'Arco tangente das coordenadas x e y.'],
  ['RADIANS', 'Matemática', 'graus', 'Converte graus em radianos.'],
  ['DEGREES', 'Matemática', 'radianos', 'Converte radianos em graus.'],
  ['FACT', 'Matemática', 'núm', 'Fatorial.'],
  ['GCD', 'Matemática', 'núm1; [núm2]; …', 'Máximo divisor comum.'],
  ['LCM', 'Matemática', 'núm1; [núm2]; …', 'Mínimo múltiplo comum.'],
  ['RAND', 'Matemática', '', 'Número aleatório entre 0 e 1.'],
  ['RANDBETWEEN', 'Matemática', 'mínimo; máximo', 'Inteiro aleatório no intervalo.'],
  ['SUBTOTAL', 'Matemática', 'função; ref1; …', 'Subtotal com função numerada (9 = soma, 1 = média…).'],
  ['MMULT', 'Matemática', 'matriz1; matriz2', 'Produto de matrizes.'],
  ['TRANSPOSE', 'Busca e referência', 'matriz', 'Transpõe linhas e colunas.'],

  ['IF', 'Lógica', 'teste; valor_se_verdadeiro; [valor_se_falso]', 'Retorna um valor se o teste for verdadeiro e outro se for falso.'],
  ['IFS', 'Lógica', 'teste1; valor1; [teste2; valor2]; …', 'Avalia vários testes e retorna o valor do primeiro verdadeiro.'],
  ['IFERROR', 'Lógica', 'valor; valor_se_erro', 'Retorna um valor alternativo se a fórmula resultar em erro.'],
  ['IFNA', 'Lógica', 'valor; valor_se_nd', 'Retorna um valor alternativo se o resultado for #N/D.'],
  ['AND', 'Lógica', 'lógico1; [lógico2]; …', 'Verdadeiro se todos os argumentos forem verdadeiros.'],
  ['OR', 'Lógica', 'lógico1; [lógico2]; …', 'Verdadeiro se algum argumento for verdadeiro.'],
  ['NOT', 'Lógica', 'lógico', 'Inverte verdadeiro e falso.'],
  ['XOR', 'Lógica', 'lógico1; [lógico2]; …', 'OU exclusivo.'],
  ['SWITCH', 'Lógica', 'expressão; valor1; resultado1; …; [padrão]', 'Compara a expressão com uma lista de valores.'],
  ['TRUE', 'Lógica', '', 'Valor lógico verdadeiro.'],
  ['FALSE', 'Lógica', '', 'Valor lógico falso.'],

  ['AVERAGE', 'Estatística', 'núm1; [núm2]; …', 'Média aritmética.'],
  ['AVERAGEIF', 'Estatística', 'intervalo; critério; [intervalo_média]', 'Média das células que atendem a um critério.'],
  ['MODE', 'Estatística', 'matriz', 'Valor mais frequente.'],
  ['RANK', 'Estatística', 'núm; ref; [ordem]', 'Posição de um número em uma lista (0 = decrescente).'],
  ['INTERCEPT', 'Estatística', 'y_conhecidos; x_conhecidos', 'Intercepção da reta de regressão linear.'],
  ['MEDIAN', 'Estatística', 'núm1; [núm2]; …', 'Mediana.'],
  ['MAX', 'Estatística', 'núm1; [núm2]; …', 'Maior valor.'],
  ['MIN', 'Estatística', 'núm1; [núm2]; …', 'Menor valor.'],
  ['MAXIFS', 'Estatística', 'intervalo_máx; intervalo1; critério1; …', 'Maior valor entre as células que atendem aos critérios.'],
  ['MINIFS', 'Estatística', 'intervalo_mín; intervalo1; critério1; …', 'Menor valor entre as células que atendem aos critérios.'],
  ['LARGE', 'Estatística', 'matriz; k', 'O k-ésimo maior valor.'],
  ['SMALL', 'Estatística', 'matriz; k', 'O k-ésimo menor valor.'],
  ['COUNT', 'Estatística', 'valor1; [valor2]; …', 'Conta células com números.'],
  ['COUNTA', 'Estatística', 'valor1; [valor2]; …', 'Conta células não vazias.'],
  ['COUNTBLANK', 'Estatística', 'intervalo', 'Conta células vazias.'],
  ['COUNTIF', 'Estatística', 'intervalo; critério', 'Conta células que atendem a um critério.'],
  ['COUNTIFS', 'Estatística', 'intervalo1; critério1; …', 'Conta células que atendem a vários critérios.'],
  ['STDEV.S', 'Estatística', 'núm1; [núm2]; …', 'Desvio padrão amostral.'],
  ['STDEV.P', 'Estatística', 'núm1; [núm2]; …', 'Desvio padrão populacional.'],
  ['VAR.S', 'Estatística', 'núm1; [núm2]; …', 'Variância amostral.'],
  ['VAR.P', 'Estatística', 'núm1; [núm2]; …', 'Variância populacional.'],
  ['PERCENTILE.INC', 'Estatística', 'matriz; k', 'Percentil (k entre 0 e 1).'],
  ['QUARTILE.INC', 'Estatística', 'matriz; quartil', 'Quartil (0 a 4).'],
  ['CORREL', 'Estatística', 'matriz1; matriz2', 'Coeficiente de correlação.'],
  ['SLOPE', 'Estatística', 'y_conhecidos; x_conhecidos', 'Inclinação da reta de regressão linear.'],
  ['RSQ', 'Estatística', 'y_conhecidos; x_conhecidos', 'Coeficiente de determinação R².'],
  ['NORM.DIST', 'Estatística', 'x; média; desvio; acumulado', 'Distribuição normal.'],
  ['NORM.INV', 'Estatística', 'probabilidade; média; desvio', 'Inverso da distribuição normal.'],

  ['LEFT', 'Texto', 'texto; [núm_caract]', 'Primeiros caracteres do texto.'],
  ['RIGHT', 'Texto', 'texto; [núm_caract]', 'Últimos caracteres do texto.'],
  ['MID', 'Texto', 'texto; início; núm_caract', 'Caracteres a partir de uma posição.'],
  ['LEN', 'Texto', 'texto', 'Número de caracteres.'],
  ['FIND', 'Texto', 'procurado; texto; [início]', 'Posição de um texto dentro de outro (diferencia maiúsculas).'],
  ['SEARCH', 'Texto', 'procurado; texto; [início]', 'Posição de um texto dentro de outro (não diferencia maiúsculas).'],
  ['SUBSTITUTE', 'Texto', 'texto; antigo; novo; [instância]', 'Substitui um trecho do texto.'],
  ['REPLACE', 'Texto', 'texto; início; núm_caract; novo', 'Substitui caracteres por posição.'],
  ['UPPER', 'Texto', 'texto', 'Converte para maiúsculas.'],
  ['LOWER', 'Texto', 'texto', 'Converte para minúsculas.'],
  ['PROPER', 'Texto', 'texto', 'Primeira letra de cada palavra em maiúscula.'],
  ['TRIM', 'Texto', 'texto', 'Remove espaços extras.'],
  ['CONCATENATE', 'Texto', 'texto1; [texto2]; …', 'Junta textos.'],
  ['TEXTJOIN', 'Texto', 'delimitador; ignorar_vazias; texto1; …', 'Junta textos com um delimitador.'],
  ['TEXT', 'Texto', 'valor; formato', 'Converte um valor em texto com um formato (ex.: "0,00").'],
  ['VALUE', 'Texto', 'texto', 'Converte texto em número.'],
  ['REPT', 'Texto', 'texto; vezes', 'Repete um texto.'],
  ['EXACT', 'Texto', 'texto1; texto2', 'Verdadeiro se os textos forem idênticos.'],
  ['CHAR', 'Texto', 'núm', 'Caractere de um código.'],
  ['CODE', 'Texto', 'texto', 'Código do primeiro caractere.'],

  ['DATE', 'Data e hora', 'ano; mês; dia', 'Monta uma data.'],
  ['TODAY', 'Data e hora', '', 'Data de hoje.'],
  ['NOW', 'Data e hora', '', 'Data e hora atuais.'],
  ['YEAR', 'Data e hora', 'data', 'Ano de uma data.'],
  ['MONTH', 'Data e hora', 'data', 'Mês de uma data.'],
  ['DAY', 'Data e hora', 'data', 'Dia de uma data.'],
  ['WEEKDAY', 'Data e hora', 'data; [tipo]', 'Dia da semana (1 = domingo, por padrão).'],
  ['DATEDIF', 'Data e hora', 'início; fim; unidade', 'Diferença entre datas em "Y", "M" ou "D".'],
  ['DAYS', 'Data e hora', 'fim; início', 'Dias entre duas datas.'],
  ['EDATE', 'Data e hora', 'data; meses', 'Data deslocada em meses.'],
  ['EOMONTH', 'Data e hora', 'data; meses', 'Último dia do mês, deslocado em meses.'],
  ['NETWORKDAYS', 'Data e hora', 'início; fim; [feriados]', 'Dias úteis entre duas datas.'],
  ['WORKDAY', 'Data e hora', 'início; dias; [feriados]', 'Data após um número de dias úteis.'],
  ['YEARFRAC', 'Data e hora', 'início; fim; [base]', 'Fração do ano entre duas datas.'],
  ['TIME', 'Data e hora', 'hora; minuto; segundo', 'Monta um horário.'],

  ['VLOOKUP', 'Busca e referência', 'valor; tabela; col_índice; [aproximado]', 'Procura na primeira coluna e retorna o valor de outra coluna da mesma linha (use 0 para correspondência exata).'],
  ['HLOOKUP', 'Busca e referência', 'valor; tabela; lin_índice; [aproximado]', 'Procura na primeira linha e retorna o valor de outra linha da mesma coluna.'],
  ['INDEX', 'Busca e referência', 'matriz; linha; [coluna]', 'Valor em uma posição da matriz.'],
  ['MATCH', 'Busca e referência', 'valor; matriz; [tipo]', 'Posição de um valor em uma lista (0 = exato).'],
  ['CHOOSE', 'Busca e referência', 'índice; valor1; [valor2]; …', 'Escolhe um valor pelo índice.'],
  ['OFFSET', 'Busca e referência', 'ref; linhas; colunas; [altura]; [largura]', 'Referência deslocada.'],
  ['ROW', 'Busca e referência', '[ref]', 'Número da linha.'],
  ['COLUMN', 'Busca e referência', '[ref]', 'Número da coluna.'],
  ['ROWS', 'Busca e referência', 'matriz', 'Quantidade de linhas.'],
  ['COLUMNS', 'Busca e referência', 'matriz', 'Quantidade de colunas.'],
  ['ADDRESS', 'Busca e referência', 'linha; coluna; [abs]; [a1]; [planilha]', 'Endereço de célula como texto.'],

  ['ISNUMBER', 'Informação', 'valor', 'Verdadeiro se for número.'],
  ['ISTEXT', 'Informação', 'valor', 'Verdadeiro se for texto.'],
  ['ISBLANK', 'Informação', 'valor', 'Verdadeiro se a célula estiver vazia.'],
  ['ISERROR', 'Informação', 'valor', 'Verdadeiro se for qualquer erro.'],
  ['ISEVEN', 'Informação', 'núm', 'Verdadeiro se for par.'],
  ['ISODD', 'Informação', 'núm', 'Verdadeiro se for ímpar.'],
  ['NA', 'Informação', '', 'Retorna o erro #N/D.'],

  ['PMT', 'Financeira', 'taxa; nper; vp; [vf]; [tipo]', 'Pagamento periódico de um financiamento.'],
  ['FV', 'Financeira', 'taxa; nper; pgto; [vp]; [tipo]', 'Valor futuro.'],
  ['PV', 'Financeira', 'taxa; nper; pgto; [vf]; [tipo]', 'Valor presente.'],
  ['NPV', 'Financeira', 'taxa; valor1; [valor2]; …', 'Valor presente líquido.'],
  ['IRR', 'Financeira', 'valores; [estimativa]', 'Taxa interna de retorno.'],
  ['RATE', 'Financeira', 'nper; pgto; vp; [vf]; [tipo]; [estimativa]', 'Taxa de juros por período.'],
  ['NPER', 'Financeira', 'taxa; pgto; vp; [vf]; [tipo]', 'Número de períodos.'],
  ['IPMT', 'Financeira', 'taxa; período; nper; vp', 'Juros de um período.'],
  ['PPMT', 'Financeira', 'taxa; período; nper; vp', 'Amortização de um período.'],

  ['XLOOKUP', 'Busca e referência', 'procurado; onde_procurar; retorno; [se_não_achar]', 'Busca em uma coluna ou linha e retorna o valor correspondente (substitui PROCV/PROCH).'],
  ['CONVERT', 'Engenharia', 'núm; de_unidade; para_unidade', 'Converte unidades (ex.: "m"→"ft", "N"→"lbf", "Pa"→"psi").'],
  ['DEC2BIN', 'Engenharia', 'núm; [casas]', 'Decimal para binário.'],
  ['BIN2DEC', 'Engenharia', 'núm', 'Binário para decimal.'],
  ['DEC2HEX', 'Engenharia', 'núm; [casas]', 'Decimal para hexadecimal.'],
  ['HEX2DEC', 'Engenharia', 'núm', 'Hexadecimal para decimal.'],
  ['ERF', 'Engenharia', 'limite_inf; [limite_sup]', 'Função erro.']
]

export const CATALOGO = L.map(([k, cat, args, desc]) => ({ k, cat, args, desc, nome: nomeLocal(k), sintaxe: `${nomeLocal(k)}(${args})` }))
export const CATEGORIAS = [...new Set(CATALOGO.map((f) => f.cat))]
const POR_NOME = new Map(CATALOGO.map((f) => [f.nome, f]))
export const infoFuncao = (nomeLocalMaiusculo) => POR_NOME.get(nomeLocalMaiusculo)
